/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 * For more detailed information on multi-project builds, please refer to https://docs.gradle.org/8.7/userguide/multi_project_builds.html in the Gradle documentation.
 */

rootProject.name = "Web-Resolver-Task"


dependencyResolutionManagement {
    repositories {
        mavenCentral()
    }

    versionCatalogs {
        create("libs") {
            from(files("gradle/catalog-version/libs.versions.toml"))
        }
    }

}

pluginManagement {
    repositories {
        gradlePluginPortal()
        mavenCentral()
    }
}
include(
    "api-generator",
    "task-resolver",
    "common",
    "task-process",
    "MainApplication",
    "db"
)
