/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 * For more detailed information on multi-project builds, please refer to https://docs.gradle.org/8.7/userguide/multi_project_builds.html in the Gradle documentation.
 */

rootProject.name = "Web-Resolver-Task"


dependencyResolutionManagement {
    repositories {
        mavenCentral()
    }

    versionCatalogs {
        create("libs") {
            from(files("gradle/catalog-version/libs.versions.toml"))
        }
    }

}

pluginManagement {
    repositories {
        gradlePluginPortal()
        mavenCentral()
        google()
    }
    plugins {
        kotlin("jvm") version "2.2.21"
        kotlin("plugin.spring") version "2.2.21"
        kotlin("plugin.jpa") version "2.2.21"
        id("org.springframework.boot") version "3.5.0"
        id("io.spring.dependency-management") version "1.1.7"
        id("org.openapi.generator") version "7.17.0"
    }
}
include(
    "api-generator",
    "task-resolver",
    "common",
    "MainApplication",
    "db",
    "sandbox",
    "worker",
    "ai-analyzer",
    "scenario-runner"
)
