spring:
  datasource:
    url: jdbc:postgresql://localhost:7909/postgres
    username: user
    password: user
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 0
      connection-timeout: 30000
      transaction-isolation: TRANSACTION_READ_COMMITTED
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        connection:
          url: ${spring.datasource.url}
          username: ${spring.datasource.username}
          password: ${spring.datasource.password}
          pool_size: ${spring.datasource.hikari.maximum-pool-size}
          isolation: ${spring.datasource.hikari.transaction-isolation}

  liquibase:
    enabled: true
    change-log: classpath:migration/db/changelog.xml


kafka:
  config:
    task-cluster:
      bootstrap-servers: localhost:9092
